/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* \nmigen.hierarchy  = "Cfu" *)
(* top =  1  *)
(* generator = "nMigen" *)
module Cfu(cmd_ready, cmd_payload_function_id, cmd_payload_inputs_0, cmd_payload_inputs_1, rsp_valid, rsp_ready, rsp_payload_outputs_0, reset, port0_addr, port1_addr, port2_addr, port3_addr, port0_din, port1_din, port2_din, port3_din, clk, rst, cmd_valid);
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:250" *)
  reg [31:0] \$signal ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:251" *)
  reg \$signal$1 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:250" *)
  reg [31:0] \$signal$10 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:251" *)
  reg \$signal$11 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:252" *)
  reg \$signal$13 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:250" *)
  reg [31:0] \$signal$14 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:251" *)
  reg \$signal$15 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:252" *)
  reg \$signal$17 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:250" *)
  reg [31:0] \$signal$18 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:251" *)
  reg \$signal$19 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:252" *)
  reg \$signal$2 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:252" *)
  reg \$signal$21 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:250" *)
  reg [31:0] \$signal$22 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:251" *)
  reg \$signal$23 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:252" *)
  reg \$signal$25 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:250" *)
  reg [31:0] \$signal$26 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:251" *)
  reg \$signal$27 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:252" *)
  reg \$signal$29 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:250" *)
  reg [31:0] \$signal$3 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:251" *)
  reg \$signal$4 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:252" *)
  reg \$signal$5 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:250" *)
  reg [31:0] \$signal$6 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:251" *)
  reg \$signal$7 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:252" *)
  reg \$signal$9 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/third_party/python/nmigen/nmigen/hdl/ir.py:524" *)
  input clk;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:184" *)
  input [9:0] cmd_payload_function_id;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:186" *)
  input [31:0] cmd_payload_inputs_0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:187" *)
  input [31:0] cmd_payload_inputs_1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:183" *)
  output cmd_ready;
  reg cmd_ready;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:182" *)
  input cmd_valid;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:246" *)
  reg current_function_done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:245" *)
  reg [2:0] current_function_id;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  wire fallback1_done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  reg [31:0] fallback1_in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  reg [31:0] fallback1_in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  wire [31:0] fallback1_output;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  wire fallback2_done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  reg [31:0] fallback2_in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  reg [31:0] fallback2_in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  wire [31:0] fallback2_output;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  wire fallback3_done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  reg [31:0] fallback3_in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  reg [31:0] fallback3_in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  wire [31:0] fallback3_output;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  wire fallback4_done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  reg [31:0] fallback4_in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  reg [31:0] fallback4_in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  wire [31:0] fallback4_output;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  wire fallback5_done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  reg [31:0] fallback5_in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  reg [31:0] fallback5_in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  wire [31:0] fallback5_output;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  wire fallback6_done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  reg [31:0] fallback6_in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  reg [31:0] fallback6_in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  wire [31:0] fallback6_output;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  wire fallback7_done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  reg [31:0] fallback7_in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  reg [31:0] fallback7_in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  wire [31:0] fallback7_output;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  wire fn0_done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  reg [31:0] fn0_in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  reg [31:0] fn0_in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  wire [31:0] fn0_output;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:52" *)
  reg fn0_start;
  (* init = 2'h0 *)
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:238" *)
  reg [2:0] funct3;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:239" *)
  reg [6:0] funct7;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:50" *)
  reg [6:0] \funct7$30 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:50" *)
  reg [6:0] \funct7$31 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:50" *)
  reg [6:0] \funct7$32 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:50" *)
  reg [6:0] \funct7$33 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:50" *)
  reg [6:0] \funct7$34 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:50" *)
  reg [6:0] \funct7$35 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:50" *)
  reg [6:0] \funct7$36 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:50" *)
  reg [6:0] \funct7$37 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:192" *)
  input [31:0] port0_addr;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:193" *)
  input [31:0] port0_din;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:192" *)
  input [31:0] port1_addr;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:193" *)
  input [31:0] port1_din;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:192" *)
  input [31:0] port2_addr;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:193" *)
  input [31:0] port2_din;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:192" *)
  input [31:0] port3_addr;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:193" *)
  input [31:0] port3_din;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:191" *)
  input reset;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:190" *)
  output [31:0] rsp_payload_outputs_0;
  reg [31:0] rsp_payload_outputs_0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:189" *)
  input rsp_ready;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:188" *)
  output rsp_valid;
  reg rsp_valid;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/third_party/python/nmigen/nmigen/hdl/ir.py:524" *)
  output rst;
  reg rst;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:52" *)
  reg start;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:52" *)
  reg \start$12 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:52" *)
  reg \start$16 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:52" *)
  reg \start$20 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:52" *)
  reg \start$24 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:52" *)
  reg \start$28 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:52" *)
  reg \start$8 ;
  (* init = 3'h0 *)
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:244" *)
  reg [2:0] stored_function_id = 3'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:244" *)
  reg [2:0] \stored_function_id$next ;
  (* init = 32'd0 *)
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:247" *)
  reg [31:0] stored_output = 32'd0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:247" *)
  reg [31:0] \stored_output$next ;
  always @(posedge clk)
      stored_output <= \stored_output$next ;
  always @(posedge clk)
      fsm_state <= \fsm_state$next ;
  always @(posedge clk)
      stored_function_id <= \stored_function_id$next ;
  fallback1 fallback1 (
    .done(fallback1_done),
    .in0(fallback1_in0),
    .in1(fallback1_in1),
    .\output (fallback1_output)
  );
  fallback2 fallback2 (
    .done(fallback2_done),
    .in0(fallback2_in0),
    .in1(fallback2_in1),
    .\output (fallback2_output)
  );
  fallback3 fallback3 (
    .done(fallback3_done),
    .in0(fallback3_in0),
    .in1(fallback3_in1),
    .\output (fallback3_output)
  );
  fallback4 fallback4 (
    .done(fallback4_done),
    .in0(fallback4_in0),
    .in1(fallback4_in1),
    .\output (fallback4_output)
  );
  fallback5 fallback5 (
    .done(fallback5_done),
    .in0(fallback5_in0),
    .in1(fallback5_in1),
    .\output (fallback5_output)
  );
  fallback6 fallback6 (
    .done(fallback6_done),
    .in0(fallback6_in0),
    .in1(fallback6_in1),
    .\output (fallback6_output)
  );
  fallback7 fallback7 (
    .done(fallback7_done),
    .in0(fallback7_in0),
    .in1(fallback7_in1),
    .\output (fallback7_output)
  );
  fn0 fn0 (
    .clk(clk),
    .done(fn0_done),
    .in0(fn0_in0),
    .in1(fn0_in1),
    .\output (fn0_output),
    .rst(rst),
    .start(fn0_start)
  );
  always @* begin
    funct3 = 3'h0;
    funct3 = cmd_payload_function_id[2:0];
  end
  always @* begin
    funct7 = 7'h00;
    funct7 = cmd_payload_function_id[9:3];
  end
  always @* begin
    \start$8  = 1'h0;
    \start$8  = \$signal$9 ;
  end
  always @* begin
    \$signal$10  = 32'd0;
    \$signal$10  = fallback3_output;
  end
  always @* begin
    \$signal$11  = 1'h0;
    \$signal$11  = fallback3_done;
  end
  always @* begin
    \start$12  = 1'h0;
    \start$12  = \$signal$13 ;
  end
  always @* begin
    \$signal$14  = 32'd0;
    \$signal$14  = fallback4_output;
  end
  always @* begin
    \$signal$15  = 1'h0;
    \$signal$15  = fallback4_done;
  end
  always @* begin
    \start$16  = 1'h0;
    \start$16  = \$signal$17 ;
  end
  always @* begin
    \$signal$18  = 32'd0;
    \$signal$18  = fallback5_output;
  end
  always @* begin
    \$signal$19  = 1'h0;
    \$signal$19  = fallback5_done;
  end
  always @* begin
    \start$20  = 1'h0;
    \start$20  = \$signal$21 ;
  end
  always @* begin
    \$signal  = 32'd0;
    \$signal  = fn0_output;
  end
  always @* begin
    \$signal$22  = 32'd0;
    \$signal$22  = fallback6_output;
  end
  always @* begin
    \$signal$23  = 1'h0;
    \$signal$23  = fallback6_done;
  end
  always @* begin
    \start$24  = 1'h0;
    \start$24  = \$signal$25 ;
  end
  always @* begin
    \$signal$26  = 32'd0;
    \$signal$26  = fallback7_output;
  end
  always @* begin
    \$signal$27  = 1'h0;
    \$signal$27  = fallback7_done;
  end
  always @* begin
    \start$28  = 1'h0;
    \start$28  = \$signal$29 ;
  end
  always @* begin
    current_function_id = 3'h0;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \nmigen.decoding  = "WAIT_CMD/0" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:273" */
      2'h0:
          current_function_id = funct3;
      /* \nmigen.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:284" */
      2'h2:
          current_function_id = stored_function_id;
    endcase
  end
  always @* begin
    current_function_done = 1'h0;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \nmigen.decoding  = "WAIT_CMD/0" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:277" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$7 ;
            3'h3:
                current_function_done = \$signal$11 ;
            3'h4:
                current_function_done = \$signal$15 ;
            3'h5:
                current_function_done = \$signal$19 ;
            3'h6:
                current_function_done = \$signal$23 ;
            3'hz:
                current_function_done = \$signal$27 ;
          endcase
      /* \nmigen.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:289" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$7 ;
            3'h3:
                current_function_done = \$signal$11 ;
            3'h4:
                current_function_done = \$signal$15 ;
            3'h5:
                current_function_done = \$signal$19 ;
            3'h6:
                current_function_done = \$signal$23 ;
            3'hz:
                current_function_done = \$signal$27 ;
          endcase
    endcase
  end
  always @* begin
    cmd_ready = 1'h0;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \nmigen.decoding  = "WAIT_CMD/0" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:273" */
      2'h0:
          cmd_ready = 1'h1;
    endcase
  end
  always @* begin
    \stored_function_id$next  = stored_function_id;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \nmigen.decoding  = "WAIT_CMD/0" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" */
            1'h1:
                \stored_function_id$next  = cmd_payload_function_id[2:0];
          endcase
    endcase
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/third_party/python/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stored_function_id$next  = 3'h0;
    endcase
  end
  always @* begin
    \$signal$1  = 1'h0;
    \$signal$1  = fn0_done;
  end
  always @* begin
    \$signal$2  = 1'h0;
    \$signal$5  = 1'h0;
    \$signal$9  = 1'h0;
    \$signal$13  = 1'h0;
    \$signal$17  = 1'h0;
    \$signal$21  = 1'h0;
    \$signal$25  = 1'h0;
    \$signal$29  = 1'h0;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \nmigen.decoding  = "WAIT_CMD/0" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:282" *)
                casez (current_function_id)
                  3'h0:
                      \$signal$2  = 1'h1;
                  3'h1:
                      \$signal$5  = 1'h1;
                  3'h2:
                      \$signal$9  = 1'h1;
                  3'h3:
                      \$signal$13  = 1'h1;
                  3'h4:
                      \$signal$17  = 1'h1;
                  3'h5:
                      \$signal$21  = 1'h1;
                  3'h6:
                      \$signal$25  = 1'h1;
                  3'hz:
                      \$signal$29  = 1'h1;
                endcase
          endcase
    endcase
  end
  always @* begin
    rsp_valid = 1'h0;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \nmigen.decoding  = "WAIT_CMD/0" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" */
                  1'h1:
                      rsp_valid = 1'h1;
                endcase
          endcase
      /* \nmigen.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" */
            1'h1:
                rsp_valid = 1'h1;
          endcase
      /* \nmigen.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:291" */
      2'h1:
          rsp_valid = 1'h1;
    endcase
  end
  always @* begin
    rsp_payload_outputs_0 = 32'd0;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \nmigen.decoding  = "WAIT_CMD/0" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" */
                  1'h1:
                      (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:262" *)
                      casez (current_function_id)
                        3'h0:
                            rsp_payload_outputs_0 = \$signal ;
                        3'h1:
                            rsp_payload_outputs_0 = \$signal$3 ;
                        3'h2:
                            rsp_payload_outputs_0 = \$signal$6 ;
                        3'h3:
                            rsp_payload_outputs_0 = \$signal$10 ;
                        3'h4:
                            rsp_payload_outputs_0 = \$signal$14 ;
                        3'h5:
                            rsp_payload_outputs_0 = \$signal$18 ;
                        3'h6:
                            rsp_payload_outputs_0 = \$signal$22 ;
                        3'hz:
                            rsp_payload_outputs_0 = \$signal$26 ;
                      endcase
                endcase
          endcase
      /* \nmigen.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" */
            1'h1:
                (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:262" *)
                casez (current_function_id)
                  3'h0:
                      rsp_payload_outputs_0 = \$signal ;
                  3'h1:
                      rsp_payload_outputs_0 = \$signal$3 ;
                  3'h2:
                      rsp_payload_outputs_0 = \$signal$6 ;
                  3'h3:
                      rsp_payload_outputs_0 = \$signal$10 ;
                  3'h4:
                      rsp_payload_outputs_0 = \$signal$14 ;
                  3'h5:
                      rsp_payload_outputs_0 = \$signal$18 ;
                  3'h6:
                      rsp_payload_outputs_0 = \$signal$22 ;
                  3'hz:
                      rsp_payload_outputs_0 = \$signal$26 ;
                endcase
          endcase
      /* \nmigen.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:291" */
      2'h1:
          rsp_payload_outputs_0 = stored_output;
    endcase
  end
  always @* begin
    fn0_start = 1'h0;
    fn0_start = \$signal$2 ;
  end
  always @* begin
    \fsm_state$next  = fsm_state;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \nmigen.decoding  = "WAIT_CMD/0" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" */
                  1'h1:
                      (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:263" *)
                      casez (rsp_ready)
                        /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:263" */
                        1'h1:
                            \fsm_state$next  = 2'h0;
                        /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:265" */
                        default:
                            \fsm_state$next  = 2'h1;
                      endcase
                  /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:269" */
                  default:
                      \fsm_state$next  = 2'h2;
                endcase
          endcase
      /* \nmigen.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" */
            1'h1:
                (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:263" *)
                casez (rsp_ready)
                  /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:263" */
                  1'h1:
                      \fsm_state$next  = 2'h0;
                  /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:265" */
                  default:
                      \fsm_state$next  = 2'h1;
                endcase
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:269" */
            default:
                \fsm_state$next  = 2'h2;
          endcase
      /* \nmigen.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:291" */
      2'h1:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:296" *)
          casez (rsp_ready)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:296" */
            1'h1:
                \fsm_state$next  = 2'h0;
          endcase
    endcase
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/third_party/python/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 2'h0;
    endcase
  end
  always @* begin
    \stored_output$next  = stored_output;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \nmigen.decoding  = "WAIT_CMD/0" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" *)
          casez (cmd_valid)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:279" */
            1'h1:
                (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" *)
                casez (current_function_done)
                  /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" */
                  1'h1:
                      (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:263" *)
                      casez (rsp_ready)
                        /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:263" */
                        1'h1:
                            /* empty */;
                        /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:265" */
                        default:
                            (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:267" *)
                            casez (current_function_id)
                              3'h0:
                                  \stored_output$next  = \$signal ;
                              3'h1:
                                  \stored_output$next  = \$signal$3 ;
                              3'h2:
                                  \stored_output$next  = \$signal$6 ;
                              3'h3:
                                  \stored_output$next  = \$signal$10 ;
                              3'h4:
                                  \stored_output$next  = \$signal$14 ;
                              3'h5:
                                  \stored_output$next  = \$signal$18 ;
                              3'h6:
                                  \stored_output$next  = \$signal$22 ;
                              3'hz:
                                  \stored_output$next  = \$signal$26 ;
                            endcase
                      endcase
                endcase
          endcase
      /* \nmigen.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" *)
          casez (current_function_done)
            /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:259" */
            1'h1:
                (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:263" *)
                casez (rsp_ready)
                  /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:263" */
                  1'h1:
                      /* empty */;
                  /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:265" */
                  default:
                      (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:267" *)
                      casez (current_function_id)
                        3'h0:
                            \stored_output$next  = \$signal ;
                        3'h1:
                            \stored_output$next  = \$signal$3 ;
                        3'h2:
                            \stored_output$next  = \$signal$6 ;
                        3'h3:
                            \stored_output$next  = \$signal$10 ;
                        3'h4:
                            \stored_output$next  = \$signal$14 ;
                        3'h5:
                            \stored_output$next  = \$signal$18 ;
                        3'h6:
                            \stored_output$next  = \$signal$22 ;
                        3'hz:
                            \stored_output$next  = \$signal$26 ;
                      endcase
                endcase
          endcase
    endcase
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/third_party/python/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \stored_output$next  = 32'd0;
    endcase
  end
  always @* begin
    fn0_in0 = 32'd0;
    fn0_in0 = cmd_payload_inputs_0;
  end
  always @* begin
    fn0_in1 = 32'd0;
    fn0_in1 = cmd_payload_inputs_1;
  end
  always @* begin
    \funct7$30  = 7'h00;
    \funct7$30  = funct7;
  end
  always @* begin
    fallback1_in0 = 32'd0;
    fallback1_in0 = cmd_payload_inputs_0;
  end
  always @* begin
    fallback1_in1 = 32'd0;
    fallback1_in1 = cmd_payload_inputs_1;
  end
  always @* begin
    \funct7$31  = 7'h00;
    \funct7$31  = funct7;
  end
  always @* begin
    fallback2_in0 = 32'd0;
    fallback2_in0 = cmd_payload_inputs_0;
  end
  always @* begin
    fallback2_in1 = 32'd0;
    fallback2_in1 = cmd_payload_inputs_1;
  end
  always @* begin
    \$signal$3  = 32'd0;
    \$signal$3  = fallback1_output;
  end
  always @* begin
    \funct7$32  = 7'h00;
    \funct7$32  = funct7;
  end
  always @* begin
    fallback3_in0 = 32'd0;
    fallback3_in0 = cmd_payload_inputs_0;
  end
  always @* begin
    fallback3_in1 = 32'd0;
    fallback3_in1 = cmd_payload_inputs_1;
  end
  always @* begin
    \funct7$33  = 7'h00;
    \funct7$33  = funct7;
  end
  always @* begin
    fallback4_in0 = 32'd0;
    fallback4_in0 = cmd_payload_inputs_0;
  end
  always @* begin
    fallback4_in1 = 32'd0;
    fallback4_in1 = cmd_payload_inputs_1;
  end
  always @* begin
    \funct7$34  = 7'h00;
    \funct7$34  = funct7;
  end
  always @* begin
    fallback5_in0 = 32'd0;
    fallback5_in0 = cmd_payload_inputs_0;
  end
  always @* begin
    fallback5_in1 = 32'd0;
    fallback5_in1 = cmd_payload_inputs_1;
  end
  always @* begin
    \funct7$35  = 7'h00;
    \funct7$35  = funct7;
  end
  always @* begin
    \$signal$4  = 1'h0;
    \$signal$4  = fallback1_done;
  end
  always @* begin
    fallback6_in0 = 32'd0;
    fallback6_in0 = cmd_payload_inputs_0;
  end
  always @* begin
    fallback6_in1 = 32'd0;
    fallback6_in1 = cmd_payload_inputs_1;
  end
  always @* begin
    \funct7$36  = 7'h00;
    \funct7$36  = funct7;
  end
  always @* begin
    fallback7_in0 = 32'd0;
    fallback7_in0 = cmd_payload_inputs_0;
  end
  always @* begin
    fallback7_in1 = 32'd0;
    fallback7_in1 = cmd_payload_inputs_1;
  end
  always @* begin
    \funct7$37  = 7'h00;
    \funct7$37  = funct7;
  end
  always @* begin
    rst = 1'h0;
    rst = reset;
  end
  always @* begin
    start = 1'h0;
    start = \$signal$5 ;
  end
  always @* begin
    \$signal$6  = 32'd0;
    \$signal$6  = fallback2_output;
  end
  always @* begin
    \$signal$7  = 1'h0;
    \$signal$7  = fallback2_done;
  end
endmodule

(* \nmigen.hierarchy  = "Cfu.fallback1" *)
(* generator = "nMigen" *)
module fallback1(done, in0, in1, \output );
  (* init = 1'h0 *)
  reg \$verilog_initial_trigger  = 1'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  input [31:0] in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:54" *)
  reg [31:0] in0s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  input [31:0] in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:55" *)
  reg [31:0] in1s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output ;
  always @* begin
    \output  = 32'd0;
    \output  = in0;
  end
  always @* begin
    done = 1'h0;
    done = 1'h1;
    \$verilog_initial_trigger  = \$verilog_initial_trigger ;
  end
  always @* begin
    in0s = 32'd0;
    in0s = in0;
  end
  always @* begin
    in1s = 32'd0;
    in1s = in1;
  end
endmodule

(* \nmigen.hierarchy  = "Cfu.fallback2" *)
(* generator = "nMigen" *)
module fallback2(done, in0, in1, \output );
  (* init = 1'h0 *)
  reg \$verilog_initial_trigger  = 1'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  input [31:0] in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:54" *)
  reg [31:0] in0s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  input [31:0] in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:55" *)
  reg [31:0] in1s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output ;
  always @* begin
    \output  = 32'd0;
    \output  = in0;
  end
  always @* begin
    done = 1'h0;
    done = 1'h1;
    \$verilog_initial_trigger  = \$verilog_initial_trigger ;
  end
  always @* begin
    in0s = 32'd0;
    in0s = in0;
  end
  always @* begin
    in1s = 32'd0;
    in1s = in1;
  end
endmodule

(* \nmigen.hierarchy  = "Cfu.fallback3" *)
(* generator = "nMigen" *)
module fallback3(done, in0, in1, \output );
  (* init = 1'h0 *)
  reg \$verilog_initial_trigger  = 1'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  input [31:0] in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:54" *)
  reg [31:0] in0s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  input [31:0] in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:55" *)
  reg [31:0] in1s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output ;
  always @* begin
    \output  = 32'd0;
    \output  = in0;
  end
  always @* begin
    done = 1'h0;
    done = 1'h1;
    \$verilog_initial_trigger  = \$verilog_initial_trigger ;
  end
  always @* begin
    in0s = 32'd0;
    in0s = in0;
  end
  always @* begin
    in1s = 32'd0;
    in1s = in1;
  end
endmodule

(* \nmigen.hierarchy  = "Cfu.fallback4" *)
(* generator = "nMigen" *)
module fallback4(done, in0, in1, \output );
  (* init = 1'h0 *)
  reg \$verilog_initial_trigger  = 1'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  input [31:0] in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:54" *)
  reg [31:0] in0s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  input [31:0] in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:55" *)
  reg [31:0] in1s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output ;
  always @* begin
    \output  = 32'd0;
    \output  = in0;
  end
  always @* begin
    done = 1'h0;
    done = 1'h1;
    \$verilog_initial_trigger  = \$verilog_initial_trigger ;
  end
  always @* begin
    in0s = 32'd0;
    in0s = in0;
  end
  always @* begin
    in1s = 32'd0;
    in1s = in1;
  end
endmodule

(* \nmigen.hierarchy  = "Cfu.fallback5" *)
(* generator = "nMigen" *)
module fallback5(done, in0, in1, \output );
  (* init = 1'h0 *)
  reg \$verilog_initial_trigger  = 1'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  input [31:0] in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:54" *)
  reg [31:0] in0s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  input [31:0] in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:55" *)
  reg [31:0] in1s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output ;
  always @* begin
    \output  = 32'd0;
    \output  = in0;
  end
  always @* begin
    done = 1'h0;
    done = 1'h1;
    \$verilog_initial_trigger  = \$verilog_initial_trigger ;
  end
  always @* begin
    in0s = 32'd0;
    in0s = in0;
  end
  always @* begin
    in1s = 32'd0;
    in1s = in1;
  end
endmodule

(* \nmigen.hierarchy  = "Cfu.fallback6" *)
(* generator = "nMigen" *)
module fallback6(done, in0, in1, \output );
  (* init = 1'h0 *)
  reg \$verilog_initial_trigger  = 1'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  input [31:0] in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:54" *)
  reg [31:0] in0s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  input [31:0] in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:55" *)
  reg [31:0] in1s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output ;
  always @* begin
    \output  = 32'd0;
    \output  = in0;
  end
  always @* begin
    done = 1'h0;
    done = 1'h1;
    \$verilog_initial_trigger  = \$verilog_initial_trigger ;
  end
  always @* begin
    in0s = 32'd0;
    in0s = in0;
  end
  always @* begin
    in1s = 32'd0;
    in1s = in1;
  end
endmodule

(* \nmigen.hierarchy  = "Cfu.fallback7" *)
(* generator = "nMigen" *)
module fallback7(done, in0, in1, \output );
  (* init = 1'h0 *)
  reg \$verilog_initial_trigger  = 1'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  output done;
  reg done;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  input [31:0] in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:54" *)
  reg [31:0] in0s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  input [31:0] in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:55" *)
  reg [31:0] in1s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output ;
  always @* begin
    \output  = 32'd0;
    \output  = in0;
  end
  always @* begin
    done = 1'h0;
    done = 1'h1;
    \$verilog_initial_trigger  = \$verilog_initial_trigger ;
  end
  always @* begin
    in0s = 32'd0;
    in0s = in0;
  end
  always @* begin
    in1s = 32'd0;
    in1s = in1;
  end
endmodule

(* \nmigen.hierarchy  = "Cfu.fn0" *)
(* generator = "nMigen" *)
module fn0(done, start, in0, in1, rst, clk, \output );
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/proj/proj_template/cfu.py:29" *)
  wire [32:0] \$1 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/proj/proj_template/cfu.py:29" *)
  wire [32:0] \$2 ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/third_party/python/nmigen/nmigen/hdl/ir.py:524" *)
  input clk;
  (* init = 1'h0 *)
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  output done;
  reg done = 1'h0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:53" *)
  reg \done$next ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:48" *)
  input [31:0] in0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:54" *)
  reg [31:0] in0s;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:49" *)
  input [31:0] in1;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:55" *)
  reg [31:0] in1s;
  (* init = 32'd0 *)
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output  = 32'd0;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:51" *)
  reg [31:0] \output$next ;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/third_party/python/nmigen/nmigen/hdl/ir.py:524" *)
  input rst;
  (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/python/nmigen_cfu/cfu.py:52" *)
  input start;
  assign \$2  = in0 + (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/proj/proj_template/cfu.py:29" *) in1;
  always @(posedge clk)
      done <= \done$next ;
  always @(posedge clk)
      \output  <= \output$next ;
  always @* begin
    \output$next  = \output ;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/proj/proj_template/cfu.py:28" *)
    casez (start)
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/proj/proj_template/cfu.py:28" */
      1'h1:
          \output$next  = \$1 [31:0];
    endcase
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/third_party/python/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \output$next  = 32'd0;
    endcase
  end
  always @* begin
    \done$next  = done;
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/proj/proj_template/cfu.py:28" *)
    casez (start)
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/proj/proj_template/cfu.py:28" */
      1'h1:
          \done$next  = 1'h1;
      /* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/proj/proj_template/cfu.py:31" */
      default:
          \done$next  = 1'h0;
    endcase
    (* src = "/home/shivaubuntu/CFU-playground/CFU-Playground/third_party/python/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \done$next  = 1'h0;
    endcase
  end
  always @* begin
    in0s = 32'd0;
    in0s = in0;
  end
  always @* begin
    in1s = 32'd0;
    in1s = in1;
  end
  assign \$1  = \$2 ;
endmodule
