#!/bin/bash

if [ "${BASH_SOURCE-}" = "$0" ]; then
    echo -e "This script should be sourced, not run:\nsource $0" >&2
    exit 1
fi

# Exports environment variables needed by parts of this project.
#   PYTHONPATH
#   PATH

CFU_ROOT=$(dirname $(realpath ${BASH_SOURCE[0]}))
# We deliberately clear anything that may have already been in PYTHONPATH to
# prevent accidentally pulling in anything outside this project.
PYTHONPATH="${CFU_ROOT}/python"
for i in "${CFU_ROOT}/third_party/python"/* "${CFU_ROOT}/python/"*; do
    # Avoid adding files such as README.md to our path
    if [ -d "$i" ]; then
        PYTHONPATH="${PYTHONPATH}:${i}"
    fi
done
export PYTHONPATH

