#!/bin/bash
# Copyright 2021 The CFU-Playground Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

JSON="$1"
PDC="$2"
RESULT_FASM="$3"

nextpnr-nexus \
    --json "${JSON}" \
    --pdc "${PDC}" \
    --fasm "${RESULT_FASM}" \
    --device LIFCL-17-8UWG72C \
    --detailed-timing-report \
    ${EXTRA_NEXTPNR_ARGS}
