#!/bin/bash
set -e

CFU_ROOT="$(dirname $(dirname $(realpath ${BASH_SOURCE[0]})))"

UPDATE=
if [ $# -gt 1 ] ; then
  echo "Usage: install_oxide [update]"
  exit 1
fi
if [ $# -gt 0 ] ; then
  if [ $1 == "update" ] ; then
    UPDATE=1
  else
    echo "Usage: install_oxide [update]"
    exit 1
  fi
fi

if [ -z "$UPDATE" ] ; then

  echo "Sudo Installing pre-requisites"
  sudo apt update
  sudo apt install tcl-dev bison flex cmake libboost-all-dev libeigen3-dev clang

  if ! which cargo ; then
    echo "Installing Cargo"
    curl https://sh.rustup.rs -sSf | sh
    source "${HOME}/.cargo/env"
  fi

  echo
  echo "CLONING REPOSITORIES"
  cd ${CFU_ROOT}/third_party
  if [ ! -d yosys ]; then
    git clone --recursive https://github.com/YosysHQ/yosys.git
    git -C yosys pull --ff-only origin master
    git -C yosys submodule update
  fi
  if [ ! -d yosys-f4pga-plugins ]; then
    git clone --recursive https://github.com/chipsalliance/yosys-f4pga-plugins.git
    git -C yosys-f4pga-plugins pull --ff-only origin main
    git -C yosys-f4pga-plugins submodule update
  fi
  if [ ! -d prjoxide ]; then
    git clone --recursive https://github.com/gatecat/prjoxide.git
    git -C prjoxide pull --ff-only origin master
    git -C prjoxide submodule update
  fi
  if [ ! -d nextpnr ]; then
    git clone --recursive https://github.com/YosysHQ/nextpnr.git
    git -C nextpnr pull --ff-only origin master
    git -C nextpnr submodule update
  fi

else

  echo
  echo "UPDATING REPOSITORIES"
  cd "${CFU_ROOT}/third_party"
  git -C yosys pull --ff-only origin master
  git -C yosys submodule update
  git -C prjoxide pull --ff-only origin master
  git -C prjoxide submodule update
  git -C nextpnr pull --ff-only origin master
  git -C nextpnr submodule update

fi

INSTALL_ROOT=${CFU_ROOT}/third_party

echo
echo "BUILDING YOSYS"
cd "${CFU_ROOT}/third_party/yosys"
make PREFIX=${INSTALL_ROOT}/usr/local -j$(nproc)
make PREFIX=${INSTALL_ROOT}/usr/local install
export PATH="${INSTALL_ROOT}/usr/local/bin:${PATH}"

echo
echo "BUILDING YOSYS PLUGINS"
cd "${CFU_ROOT}/third_party/yosys-f4pga-plugins/dsp-ff-plugin"
YOSYS_PATH=${INSTALL_ROOT}/usr/local make -j$(nproc) all
# INSTALL_ROOT not respected in this repo, so we can't do `make install`
# make INSTALL_ROOT=${INSTALL_ROOT} install
mkdir -p "${INSTALL_ROOT}/usr/local/share/yosys/plugins"
cp "${CFU_ROOT}/third_party/yosys-f4pga-plugins/dsp-ff-plugin/dsp-ff.so" "${INSTALL_ROOT}/usr/local/share/yosys/plugins/dsp-ff.so"
cp "${CFU_ROOT}/third_party/yosys-f4pga-plugins/dsp-ff-plugin/nexus-dsp_rules.txt" "${INSTALL_ROOT}/usr/local/share/yosys/nexus/dsp_rules.txt"

echo
echo "BUILDING PRJOXIDE"
OXIDE_INSTALL_PREFIX="${INSTALL_ROOT}/.cargo"
mkdir -p "${OXIDE_INSTALL_PREFIX}"
cd "${CFU_ROOT}/third_party/prjoxide/libprjoxide"
cargo install --path prjoxide --root "${OXIDE_INSTALL_PREFIX}"
cp "${CFU_ROOT}/third_party/.cargo/bin/prjoxide" "${INSTALL_ROOT}/usr/local/bin"

echo
echo "BUILDING NEXTPNR-NEXUS"
cd "${CFU_ROOT}/third_party/nextpnr"
cmake -DCMAKE_INSTALL_PREFIX="${INSTALL_ROOT}/usr/local" -DARCH=nexus -DOXIDE_INSTALL_PREFIX="${OXIDE_INSTALL_PREFIX}" .
make -j$(nproc)
make install

echo
echo "IMPORTANT"
echo "Don't forget to add"
echo "    source \"${HOME}/.cargo/env\""
echo "to your .profile"
