#pragma once

#define NO_CFU_SIMPLIFIED 100
#define NO_CFU_VERY_ORIGINAL 200

// #define CFU_VERSION 14
// #define CFU_VERSION 12
// #define CFU_VERSION NO_CFU_SIMPLIFIED
#define CFU_VERSION NO_CFU_VERY_ORIGINAL
