name: arty_ci
on: [push, pull_request]
jobs:
  check-multi-proj:
    runs-on: ubuntu-latest
    steps:
      - run: wget --progress=dot:giga -O- https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14.tar.gz | tar -xzC /opt
      - run: echo "/opt/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: bash scripts/setup -ci
      - run: which pip3 && which python3 && which pip
      - run: make env
      - run: source env/conda/bin/activate cfu-common && which pip3 && which python3 && which pip
      - run: source env/conda/bin/activate cfu-common && riscv32-elf-gcc --version
      - run: source env/conda/bin/activate cfu-common && conda env update --file third_party/symbiflow-examples/xc7/environment.yml && pip3 install requests
      - run: source env/conda/bin/activate cfu-common && conda remove gcc-riscv64-elf-newlib -n xc7
      - run: pwd && source env/conda/bin/activate xc7 && source environment && cd proj/proj_template_v && pip3 list && make TARGET=digilent_arty EXTRA_LITEX_ARGS="--toolchain symbiflow --sys-clk-freq 75000000" bitstream
      - run: pwd && source env/conda/bin/activate xc7 && source environment && cd proj/proj_template_v && pip3 list && make TARGET=digilent_arty EXTRA_LITEX_ARGS="--toolchain symbiflow --sys-clk-freq 75000000" software
      - uses: actions/upload-artifact@v2
        with:
          name: arty-build
          path: |
            soc/build/digilent_arty.proj_template_v/gateware/digilent_arty.bit
            proj/proj_template_v/build/software.bin
            proj/proj_template_v/build/software.elf
